// Manager Events
export const MANAGER_SUCCESS_RECONNECT = "manager:successReconnect"
export const MANAGER_QUIZZ_LIST = "manager:quizzList"
export const MANAGER_GAME_CREATED = "manager:gameCreated"
export const MANAGER_STATUS_UPDATE = "manager:statusUpdate"
export const MANAGER_NEW_PLAYER = "manager:newPlayer"
export const MANAGER_REMOVE_PLAYER = "manager:removePlayer"
export const MANAGER_ERROR_MESSAGE = "manager:errorMessage"
export const MANAGER_PLAYER_KICKED = "manager:playerKicked"
export const MANAGER_AUTH = "manager:auth"
export const MANAGER_RECONNECT = "manager:reconnect"
export const MANAGER_KICK_PLAYER = "manager:kickPlayer"
export const MANAGER_START_GAME = "manager:startGame"
export const MANAGER_ABORT_QUIZ = "manager:abortQuiz"
export const MANAGER_NEXT_QUESTION = "manager:nextQuestion"
export const MANAGER_SHOW_LEADERBOARD = "manager:showLeaderboard"
